[package]
name = "gpx_reduce_points"
version = "0.1.0"
edition = "2024"

[dependencies]
geo = "0.30.0"
clap = { version = "4.5.45", features = ["derive"] }
gpx = "0.10.0"
log = "0.4.27"
env_logger = "0.11.8"