[package]
name = "gpx_to_kml"
version = "0.1.0"
edition = "2024"

[dependencies]
gpx = { version = "0.10.0", default-features = false }
kml = { version = "0.11.0", default-features = false }
thiserror = "2.0.16"
clap = { version = "4.5.45", features = ["derive"] }